# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EmWBavB2NQU8f_Ba1eY_vZCmsGpY-dVO
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
import os
from datetime import datetime
import time

# Page configuration
st.set_page_config(
    page_title="Patient Risk Prediction System",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
<style>
    .risk-low {
        background-color: #d4edda;
        color: #155724;
        padding: 10px;
        border-radius: 5px;
        font-weight: bold;
        text-align: center;
    }
    .risk-medium {
        background-color: #fff3cd;
        color: #856404;
        padding: 10px;
        border-radius: 5px;
        font-weight: bold;
        text-align: center;
    }
    .risk-high {
        background-color: #f8d7da;
        color: #721c24;
        padding: 10px;
        border-radius: 5px;
        font-weight: bold;
        text-align: center;
    }
    .alert-box {
        background-color: #dc3545;
        color: white;
        padding: 20px;
        border-radius: 10px;
        margin: 20px 0;
        font-size: 18px;
        font-weight: bold;
        animation: blink 1s infinite;
    }
    @keyframes blink {
        0%, 50%, 100% { opacity: 1; }
        25%, 75% { opacity: 0.5; }
    }
</style>
""", unsafe_allow_html=True)

# Initialize session state
if 'logged_in' not in st.session_state:
    st.session_state.logged_in = False
if 'username' not in st.session_state:
    st.session_state.username = ''
if 'patients_data' not in st.session_state:
    st.session_state.patients_data = None
if 'model' not in st.session_state:
    st.session_state.model = None

# Demo credentials
DEMO_USERS = {
    'doctor': 'doctor123',
    'admin': 'admin123'
}

def login_page():
    """Display login page"""
    st.title('🏥 Patient Risk Prediction System')
    st.subheader('Doctor Login')

    col1, col2, col3 = st.columns([1, 2, 1])

    with col2:
        st.info('Demo Credentials: doctor / doctor123 or admin / admin123')
        username = st.text_input('Username')
        password = st.text_input('Password', type='password')

        if st.button('Login', use_container_width=True):
            if username in DEMO_USERS and DEMO_USERS[username] == password:
                st.session_state.logged_in = True
                st.session_state.username = username
                st.success('Login successful!')
                st.rerun()
            else:
                st.error('Invalid username or password')

def load_model():
    """Load the trained ML model"""
    try:
        if os.path.exists('risk_model.pkl'):
            with open('risk_model.pkl', 'rb') as f:
                return pickle.load(f)
        else:
            st.warning('Model not found. Please train the model first.')
            return None
    except Exception as e:
        st.error(f'Error loading model: {str(e)}')
        return None

def generate_synthetic_patients(n=20):
    """Generate synthetic patient data"""
    np.random.seed(42)

    patients = []
    for i in range(n):
        patient = {
            'Patient_ID': f'P{1000 + i}',
            'Name': f'Patient {i+1}',
            'Age': np.random.randint(25, 85),
            'Heart_Rate': np.random.randint(50, 150),
            'Systolic_BP': np.random.randint(90, 180),
            'Diastolic_BP': np.random.randint(60, 120),
            'Oxygen_Saturation': np.random.uniform(85, 100),
            'Temperature': np.random.uniform(36.0, 40.0),
            'WBC_Count': np.random.uniform(4.0, 20.0),
            'Glucose': np.random.uniform(70, 250),
            'Timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        }
        patients.append(patient)

    return pd.DataFrame(patients)

def predict_risk(model, patient_data):
    """Predict risk level for a patient"""
    if model is None:
        return 'Unknown', 0.0

    try:
        # Extract features for prediction
        features = patient_data[[
            'Age', 'Heart_Rate', 'Systolic_BP', 'Diastolic_BP',
            'Oxygen_Saturation', 'Temperature', 'WBC_Count', 'Glucose'
        ]].values

        # Get prediction and probability
        risk_class = model.predict(features)[0]
        risk_proba = model.predict_proba(features)[0]

        risk_labels = ['Low', 'Medium', 'High']
        risk_score = risk_proba[risk_class]

        return risk_labels[risk_class], risk_score
    except Exception as e:
        st.error(f'Prediction error: {str(e)}')
        return 'Unknown', 0.0

def display_risk_badge(risk_level):
    """Display colored risk badge"""
    if risk_level == 'Low':
        return '<div class="risk-low">🟢 LOW RISK</div>'
    elif risk_level == 'Medium':
        return '<div class="risk-medium">🟡 MEDIUM RISK</div>'
    elif risk_level == 'High':
        return '<div class="risk-high">🔴 HIGH RISK</div>'
    else:
        return '<div>❓ UNKNOWN</div>'

def dashboard_page():
    """Display main dashboard"""
    st.title('🏥 Patient Risk Prediction Dashboard')
    st.write(f'Welcome, **Dr. {st.session_state.username.title()}**')

    # Logout button
    if st.sidebar.button('Logout'):
        st.session_state.logged_in = False
        st.session_state.username = ''
        st.rerun()

    # Load model
    if st.session_state.model is None:
        st.session_state.model = load_model()

    # Sidebar controls
    st.sidebar.header('Controls')
    auto_refresh = st.sidebar.checkbox('Auto-refresh (simulates real-time)', value=False)
    refresh_interval = st.sidebar.slider('Refresh interval (seconds)', 5, 60, 10)

    if st.sidebar.button('🔄 Refresh Patient Data'):
        st.session_state.patients_data = generate_synthetic_patients()
        st.success('Patient data refreshed!')

    # Generate initial data if not exists
    if st.session_state.patients_data is None:
        st.session_state.patients_data = generate_synthetic_patients()

    df = st.session_state.patients_data.copy()

    # Predict risk for all patients
    if st.session_state.model is not None:
        risk_predictions = []
        risk_scores = []

        for idx, row in df.iterrows():
            risk_level, risk_score = predict_risk(st.session_state.model, row)
            risk_predictions.append(risk_level)
            risk_scores.append(risk_score)

        df['Risk_Level'] = risk_predictions
        df['Risk_Score'] = risk_scores
    else:
        df['Risk_Level'] = 'Unknown'
        df['Risk_Score'] = 0.0
        st.warning('⚠️ Model not loaded. Please run train_model.py first.')

    # Critical alerts
    high_risk_patients = df[df['Risk_Level'] == 'High']
    if len(high_risk_patients) > 0:
        st.markdown(
            f'<div class="alert-box">🚨 CRITICAL ALERT: {len(high_risk_patients)} HIGH-RISK PATIENT(S) DETECTED!</div>',
            unsafe_allow_html=True
        )

        with st.expander('⚠️ View High-Risk Patients', expanded=True):
            for _, patient in high_risk_patients.iterrows():
                st.error(
                    f"**{patient['Name']}** (ID: {patient['Patient_ID']}) - "
                    f"Risk Score: {patient['Risk_Score']:.2%}"
                )

    # Statistics
    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric('Total Patients', len(df))
    with col2:
        low_count = len(df[df['Risk_Level'] == 'Low'])
        st.metric('Low Risk', low_count, delta_color='normal')
    with col3:
        medium_count = len(df[df['Risk_Level'] == 'Medium'])
        st.metric('Medium Risk', medium_count, delta_color='off')
    with col4:
        high_count = len(df[df['Risk_Level'] == 'High'])
        st.metric('High Risk', high_count, delta_color='inverse')

    # Patient vitals table
    st.subheader('📊 Patient Vitals & Risk Assessment')

    # Format table for display
    display_df = df[[
        'Patient_ID', 'Name', 'Age', 'Heart_Rate', 'Systolic_BP', 'Diastolic_BP',
        'Oxygen_Saturation', 'Temperature', 'WBC_Count', 'Glucose', 'Risk_Level', 'Risk_Score'
    ]].copy()

    display_df['Oxygen_Saturation'] = display_df['Oxygen_Saturation'].round(1)
    display_df['Temperature'] = display_df['Temperature'].round(1)
    display_df['WBC_Count'] = display_df['WBC_Count'].round(1)
    display_df['Glucose'] = display_df['Glucose'].round(1)
    display_df['Risk_Score'] = display_df['Risk_Score'].apply(lambda x: f'{x:.1%}')

    # Color code the dataframe
    def highlight_risk(row):
        if row['Risk_Level'] == 'High':
            return ['background-color: #f8d7da'] * len(row)
        elif row['Risk_Level'] == 'Medium':
            return ['background-color: #fff3cd'] * len(row)
        elif row['Risk_Level'] == 'Low':
            return ['background-color: #d4edda'] * len(row)
        else:
            return [''] * len(row)

    styled_df = display_df.style.apply(highlight_risk, axis=1)
    st.dataframe(styled_df, use_container_width=True, height=400)

    # Detailed patient view
    st.subheader('🔍 Detailed Patient View')
    selected_patient = st.selectbox(
        'Select a patient to view details:',
        options=df['Patient_ID'].tolist(),
        format_func=lambda x: f"{x} - {df[df['Patient_ID']==x]['Name'].values[0]}"
    )

    if selected_patient:
        patient_data = df[df['Patient_ID'] == selected_patient].iloc[0]

        col1, col2 = st.columns(2)

        with col1:
            st.write('**Patient Information**')
            st.write(f"ID: {patient_data['Patient_ID']}")
            st.write(f"Name: {patient_data['Name']}")
            st.write(f"Age: {patient_data['Age']} years")
            st.write(f"Last Updated: {patient_data['Timestamp']}")

            st.write('\n**Vital Signs**')
            st.write(f"❤️ Heart Rate: {patient_data['Heart_Rate']} bpm")
            st.write(f"🩸 Blood Pressure: {patient_data['Systolic_BP']}/{patient_data['Diastolic_BP']} mmHg")
            st.write(f"🫁 Oxygen Saturation: {patient_data['Oxygen_Saturation']:.1f}%")
            st.write(f"🌡️ Temperature: {patient_data['Temperature']:.1f}°C")

        with col2:
            st.write('**Lab Results**')
            st.write(f"🔬 WBC Count: {patient_data['WBC_Count']:.1f} K/μL")
            st.write(f"🍬 Glucose: {patient_data['Glucose']:.1f} mg/dL")

            st.write('\n**Risk Assessment**')
            st.markdown(display_risk_badge(patient_data['Risk_Level']), unsafe_allow_html=True)
            st.write(f"Risk Score: **{patient_data['Risk_Score']:.2%}**")

            if patient_data['Risk_Level'] == 'High':
                st.error('⚠️ IMMEDIATE ATTENTION REQUIRED!')
            elif patient_data['Risk_Level'] == 'Medium':
                st.warning('⚠️ Monitor closely')
            else:
                st.success('✅ Patient stable')

    # Auto-refresh
    if auto_refresh:
        time.sleep(refresh_interval)
        st.rerun()

def main():
    """Main application logic"""
    if not st.session_state.logged_in:
        login_page()
    else:
        dashboard_page()

if __name__ == '__main__':
    main()