# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EmWBavB2NQU8f_Ba1eY_vZCmsGpY-dVO
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import pickle

def generate_training_data(n_samples=1000):
    """
    Generate synthetic ICU patient data for training

    Features:
    - Age
    - Heart Rate (bpm)
    - Systolic Blood Pressure (mmHg)
    - Diastolic Blood Pressure (mmHg)
    - Oxygen Saturation (%)
    - Temperature (°C)
    - WBC Count (K/μL)
    - Glucose (mg/dL)

    Target:
    - Risk Level: 0 (Low), 1 (Medium), 2 (High)
    """
    np.random.seed(42)

    data = []

    for _ in range(n_samples):
        # Generate base patient features
        age = np.random.randint(25, 85)
        heart_rate = np.random.randint(50, 150)
        systolic_bp = np.random.randint(90, 180)
        diastolic_bp = np.random.randint(60, 120)
        oxygen_sat = np.random.uniform(85, 100)
        temperature = np.random.uniform(36.0, 40.0)
        wbc = np.random.uniform(4.0, 20.0)
        glucose = np.random.uniform(70, 250)

        # Risk scoring logic
        risk_score = 0

        # Age factor
        if age > 70:
            risk_score += 2
        elif age > 60:
            risk_score += 1

        # Heart rate factor
        if heart_rate > 120 or heart_rate < 60:
            risk_score += 2
        elif heart_rate > 100 or heart_rate < 70:
            risk_score += 1

        # Blood pressure factor
        if systolic_bp > 160 or systolic_bp < 100:
            risk_score += 2
        elif systolic_bp > 140 or systolic_bp < 110:
            risk_score += 1

        # Oxygen saturation factor
        if oxygen_sat < 90:
            risk_score += 3
        elif oxygen_sat < 94:
            risk_score += 1

        # Temperature factor
        if temperature > 38.5 or temperature < 36.0:
            risk_score += 2
        elif temperature > 37.8:
            risk_score += 1

        # WBC count factor
        if wbc > 15 or wbc < 4.5:
            risk_score += 2
        elif wbc > 12:
            risk_score += 1

        # Glucose factor
        if glucose > 200 or glucose < 80:
            risk_score += 2
        elif glucose > 150 or glucose < 90:
            risk_score += 1

        # Determine risk level based on score
        if risk_score >= 8:
            risk_level = 2  # High
        elif risk_score >= 4:
            risk_level = 1  # Medium
        else:
            risk_level = 0  # Low

        data.append([
            age, heart_rate, systolic_bp, diastolic_bp,
            oxygen_sat, temperature, wbc, glucose, risk_level
        ])

    columns = [
        'Age', 'Heart_Rate', 'Systolic_BP', 'Diastolic_BP',
        'Oxygen_Saturation', 'Temperature', 'WBC_Count', 'Glucose', 'Risk_Level'
    ]

    df = pd.DataFrame(data, columns=columns)
    return df

def train_model():
    """Train the risk prediction model"""
    print('Generating synthetic ICU patient data...')
    df = generate_training_data(n_samples=1000)

    print(f'\nDataset shape: {df.shape}')
    print(f'\nRisk level distribution:')
    print(df['Risk_Level'].value_counts())

    # Prepare features and target
    X = df.drop('Risk_Level', axis=1)
    y = df['Risk_Level']

    # Split data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    print(f'\nTraining set size: {len(X_train)}')
    print(f'Test set size: {len(X_test)}')

    # Train Random Forest model
    print('\nTraining Random Forest model...')
    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=10,
        random_state=42,
        class_weight='balanced'
    )

    model.fit(X_train, y_train)

    # Evaluate model
    print('\nEvaluating model...')
    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    print(f'\nAccuracy: {accuracy:.4f}')

    print('\nClassification Report:')
    print(classification_report(
        y_test, y_pred,
        target_names=['Low Risk', 'Medium Risk', 'High Risk']
    ))

    print('\nConfusion Matrix:')
    print(confusion_matrix(y_test, y_pred))

    # Feature importance
    feature_importance = pd.DataFrame({
        'Feature': X.columns,
        'Importance': model.feature_importances_
    }).sort_values('Importance', ascending=False)

    print('\nFeature Importance:')
    print(feature_importance)

    # Save model
    print('\nSaving model...')
    with open('risk_model.pkl', 'wb') as f:
        pickle.dump(model, f)

    print('\n✅ Model trained and saved successfully as risk_model.pkl')

    return model

if __name__ == '__main__':
    train_model()